parameters:
  versionSuffix: ''
  version: ''

steps:
- task: DotNetCoreCLI@2
  displayName: 'Compile'
  inputs:
    projects: 'src/*.sln'
    arguments: '--configuration release --version-suffix ${{ parameters.versionSuffix }} /property:Version=${{ parameters.version }}'
