parameters:
  versionSuffix: ''
  version: ''

steps:
- task: DotNetCoreCLI@2
  displayName: 'Compile'
  inputs:
    projects: 'src/*.sln'
    
    arguments: '--configuration release ${{ if ne(parameters.versionSuffix, '--version-suffix ${{ parameters.versionSuffix }}') } ${{ if ne(parameters.version, '/property:Version=${{ parameters.version }}') }'
