parameters:
  versionSuffix: ''
  version: ''

steps:
- ${{ if and(eq(parameters.version, ''), eq(parameters.versionSuffix, '')) }}:
  - task: DotNetCoreCLI@2
    displayName: 'Compile'
    inputs:
      projects: 'src/*.sln'    
      arguments: '--configuration release

- ${{ if ne(parameters.versionSuffix, '') }}:
  - task: DotNetCoreCLI@2
    displayName: 'Compile'
    inputs:
      projects: 'src/*.sln'    
      arguments: '--configuration release --version-suffix ${{ parameters.versionSuffix }}

- ${{ if ne(parameters.version, '') }}:
  - task: DotNetCoreCLI@2
    displayName: 'Compile'
    inputs:
      projects: 'src/*.sln'    
      arguments: '--configuration release /property:Version ${{ parameters.version }}

- ${{ if and(ne(parameters.version, ''), ne(parameters.versionSuffix, '')) }}:
  - task: DotNetCoreCLI@2
    displayName: 'Compile'
    inputs:
      projects: 'src/*.sln'    
      arguments: '--configuration release --version-suffix ${{ parameters.versionSuffix }} /property:Version ${{ parameters.version }}
